# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: i200937

on:
  push:
    branches: [ "i200937" ]
  pull_request:
    branches: [ "i200937" ]
permissions:
  contents: read

jobs:
  
  build:
    runs-on: [ubuntu-latest,windows-latest,macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with Pylint
      run: |
        pylint --fail-under=8 --exit-zero --max-line-length=120 src
    - name: Test with pytest
      run: |
        pytest src/test*.py
